[site]
compatibility_date = "2023-10-30"
compatibility_flags = []
workers_dev = true

[build]
command = ""
watch_dir = "./"

[build.upload]
format = "directory"

[site.static]
include = ["**/*"]
exclude = []

[[routes]]
pattern = "/*"
script = ""
style = "static" 